// data.js
export const data = [
    {
      id: '1',
      name: 'Egg Chicken Red',
      weight: '4pcs',
      price: 1.99,
      image: require('./assets/images/pngfuel 16.png'),
      category: 'Eggs',
      brand: 'Individual Collection',
    },
    {
      id: '2',
      name: 'Egg Chicken White',
      weight: '180g',
      price: 1.50,
      image: require('./assets/images/pngfuel 18.png'),
      category: 'Eggs',
      brand: 'Cocola',
    },
    {
      id: '3',
      name: 'Egg Pasta',
      weight: '30gm',
      price: 15.99,
      image: require('./assets/images/Group 6848.png'),
      category: 'Noodles & Pasta',
      brand: 'Ifad',
    },
    {
      id: '4',
      name: 'Egg Noodles',
      weight: '2L',
      price: 15.99,
      image: require('./assets/images/egg-noodle (1) 2.png'),
      category: 'Noodles & Pasta',
      brand: 'Kazi Farmas',
    },
    {
      id: '5',
      name: 'Mayonnaise Eggless',
      weight: '200g',
      price: 5.99,
      image: require('./assets/images/American-Garden-Mayonnaise-Eggless-473ml 2.png'),
      category: 'Fast Food',
      brand: 'Cocola',
    },
    {
      id: '6',
      name: 'Egg Noodles',
      weight: '2L',
      price: 15.99,
      image: require('./assets/images/rp_24790392_0053554627_l 2.png'),
      category: 'Noodles & Pasta',
      brand: 'Individual Collection',
    },
  ];